src/components/Navbar/index.jsx
src/components/Navbar/styles.scss

closes #4
**Changes**
:heavy_plus_sign: a class on navbar if url == home page
:heavy_plus_sign: css, background-color transparent for the class
* * *

4 navbar transparent on home page

---

src/assets/scss/_variables.scss
src/pages/NewPlaylist/index.jsx
src/pages/NewPlaylist/styles.scss

closes #8 
**Changes**
:heavy_plus_sign: form for new playlist with material ui component
:heavy_plus_sign: css
:heavy_plus_sign: PoppinsBoldItalic in _variables.scss
:heavy_plus_sign: api request indications as comments in onSubmit form and route
* * *

8 new playlist page

---

src/App.jsx
src/components/Navbar/index.jsx
src/pages/Login/index.jsx
src/pages/Register/index.jsx
src/redux/index.js
src/redux/log/logActions.js
src/redux/log/logReducer.js
src/redux/log/logType.js

closes #7 
**Changes**
:hammer_and_wrench: change all "connexion" to "connection" and "deconnexion" to "disconnection"
:hammer_and_wrench: eslint autofixed double quotes into single
* * *

7 correct setConnexion

---

package-lock.json
package.json
src/pages/NewPlaylist/index.jsx
src/services/APIManager/index.jsx

closes #21 
#17 
**Changes**
:heavy_plus_sign: api_manager
:heavy_plus_sign: axios setup
:hammer_and_wrench: createPlaylist method into NewPlaylist component
* * *

21 api manager

---

src/App.jsx
src/pages/NewPlaylist/index.jsx
src/services/APIManager/index.jsx

closes #17
**Changes**
:heavy_plus_sign: dynamic route for playlist show
:heavy_plus_sign: api request on submit create playlist form
:heavy_plus_sign: error messages for empty input and failure request
:hammer_and_wrench: urls and return response in api manager
* * *

17 create playlist api request

---

package-lock.json
package.json
src/pages/Playlist/index.jsx
src/pages/Playlist/styles.scss
src/services/APIManager/index.jsx
yarn.lock

closes #12 
closes #18 
**Changes**
:heavy_plus_sign: [add] material ui lab package
:heavy_plus_sign: [add] autocomplete search bar to Playlist page
:heavy_plus_sign: [add] API call to addTrackToPlaylist
:heavy_plus_sign: [add] addTrackToPlaylist to APIManager
:hammer_and_wrench: [change] baseURL from localhost to heroku prod
:hammer_and_wrench: [update] yarn.lock
* * *

12-18 track search bar component v1

---

src/pages/NewPlaylist/index.jsx
src/pages/Playlist/index.jsx
src/services/APIManager/index.jsx
src/tools/Dislikes/index.jsx
src/tools/Likes/index.jsx

closes #16 
**Changes**
:heavy_plus_sign: [add] card with likes/dislikes display system into Playlist component
:heavy_plus_sign: [add] api_manager upVote method added
:heavy_plus_sign: [add] api_manager downVote method
:hammer_and_wrench: [edit] Likes tools
:hammer_and_wrench: [fixup] Dislikes tools, refacto
:exclamation: [add] state via react hooks or Redux later
* * *

16 components up vote btn and down vote btn

---

src/pages/Playlist/index.jsx

closes #37 
**Changes**
:heavy_plus_sign: [add] sort by score and updated_at time
* * *

[add] sort by score and updated_at time

---

src/pages/Playlist/index.jsx
src/services/SpotifyAPIManager/index.js

closes #32 
**Changes**
:heavy_plus_sign: Spotify Api Manager with get track by Id method
:heavy_plus_sign: fetch track by spotify Id
:heavy_plus_sign: display of spotify info instead of back track_spotify_id
:heavy_plus_sign: autocomplete linked to spotify search api
:heavy_plus_sign: add track and like it without refresh + refresh token
* * *

#32 function interaction with spotify

---

package-lock.json
package.json
src/components/PlaylistTable/index.jsx
src/pages/Playlist/index.jsx
src/services/SpotifyAPIManager/index.js

closes #26 
**Changes**
:heavy_plus_sign: [add] template PlaylistTable component configurated
:heavy_plus_sign: [add] import PlaylistTable component
:heavy_plus_sign: [add] material icons package installed
:heavy_plus_sign: [add] music icons into playlist table
:heavy_plus_sign: [add] likes/dislikes live functionalities working into playlist component
:heavy_plus_sign: [add] import PlaylistTable component
:hammer_and_wrench: [change] updated and score sort added to Playlist Table component
:hammer_and_wrench: [fixup] Playlist page refacto
* * *

#26 summary tracks table of a playlist

---

src/pages/Playlist/index.jsx

closes #48 
**Changes**
:hammer_and_wrench: cleaning redux store trackList when the component is mounting
* * *

#48 fixed bug with new playlist by cleaning redux store trackList

---

package-lock.json
package.json
src/components/ShareButton/index.jsx
src/components/ShareButton/style.scss
src/pages/Playlist/index.jsx

closes #44
**Changes**
:heavy_plus_sign: share button component placed in playlist show page
:heavy_plus_sign: own stylesheet
* * *

#44 share button component

---

src/App.jsx
src/components/Navbar/index.jsx
src/components/PlaylistTable/index.jsx
src/constants/index.js
src/pages/Home/index.jsx
src/pages/Login/index.jsx
src/pages/NewPlaylist/index.jsx
src/pages/Playlist/index.jsx
src/pages/Register/index.jsx
src/redux/log/logReducer.js
src/redux/user/userReducer.js
src/services/APIManager/index.jsx
src/services/SpotifyAPIManager/index.js
src/tools/Authroute/index.jsx

closes #29 
**Changes**
:heavy_plus_sign: user connection info in redux
:heavy_plus_sign: sign up, sign in, sign out methods in APIManager
:heavy_plus_sign: sign up, sign in function on respective page
:heavy_plus_sign: sign out function in nav bar
:heavy_plus_sign: redirect + private page message on new-playlist and playlist pages
:hammer_and_wrench: changed all hard coded user id to real user ids
:hammer_and_wrench: fixed a display issue related to spotifyDetail on Playlist page
* * *

29 function user auth

---

src/components/Navbar/index.jsx
src/components/PlaylistTable/index.jsx
src/pages/Login/index.jsx
src/pages/NewPlaylist/index.jsx
src/pages/Playlist/index.jsx
src/pages/Register/index.jsx
src/services/SpotifyAPIManager/index.js

closes #54 
**Changes**
:heavy_plus_sign: api error handling where API calls are sent
:hammer_and_wrench: changed SpotifyAPIManager response from data to whole response
:hammer_and_wrench: fixed incoherent flash messages on log out
* * *

54 error handling for axios

---

package.json
src/components/Player/index.jsx
src/pages/Playlist/index.jsx
src/services/SpotifyAPIManager/index.js
yarn.lock

closes #53 
**Changes**
:heavy_plus_sign: react-spotify-player package
:heavy_plus_sign: Player component into Playlist page
:heavy_plus_sign: Passing spotifyDetails by props Player/Playlist
:hammer_and_wrench: yarn.lock
:hammer_and_wrench: SpotifyAPIManager Authorization
* * *

#53 display song

---

package-lock.json
src/assets/scss/_variables.scss
src/assets/scss/styles.scss
src/components/Navbar/index.jsx
src/components/Navbar/styles.scss
src/components/NewPlaylistButton/index.jsx
src/components/NewPlaylistButton/styles.scss
src/pages/Home/index.jsx
src/pages/Home/styles.scss
src/pages/Login/index.jsx
src/pages/Login/style.scss
src/pages/NewPlaylist/styles.scss
src/pages/Playlist/index.jsx
src/pages/Playlist/styles.scss
src/pages/Register/index.jsx
src/services/SpotifyAPIManager/index.js

#27
**Changes**
:heavy_plus_sign: edit design of authentication forms
:heavy_plus_sign:  edit design of home page 
:heavy_plus_sign:  edit design of new playlist page
:heavy_plus_sign:  edit design of show playlist page
:information_source: the design of the table tracks has not been done yet
* * *

#27 design and css

---

src/services/APIManager/index.jsx

**Changes**
:hammer_and_wrench: parse cookie to send only the exact token
* * *

hot-fix-jwt-token

---

src/services/APIManager/index.jsx

**Changes**
:hammer_and_wrench: fixed undefined cookie handling in token to send to MixUp back
* * *

hot-fix handle undefined cookies

---

src/components/PlaylistTable/index.jsx
src/components/PlaylistTable/styles.scss

#27 
**Changes**
:heavy_plus_sign: new design for the playlist table
* * *

[edit] design of the playlist table

---

src/components/PlaylistTable/index.jsx
src/components/PlaylistTable/styles.scss

#27 
**Changes**
:hammer_and_wrench: table scrollable with all tracks visible
* * *

#27 table scrollable with all tracks visible

---

public/index.html
src/assets/scss/_variables.scss
src/assets/scss/styles.scss
src/components/Navbar/index.jsx
src/components/Navbar/styles.scss
src/components/PlaylistTable/index.jsx
src/pages/Playlist/index.jsx
src/pages/Playlist/styles.scss
src/redux/tracklist/tracklistActions.js
src/redux/tracklist/tracklistReducer.js

closes #46 (not closed, waiting for other minor issues)
**Changes**
:heavy_plus_sign: CTA to create new playlist in nav bar
:heavy_plus_sign: CTA to create a new playlist in any page of playlist with at lease a track
:heavy_plus_sign: shadow around playlist table
:heavy_plus_sign: playlist name and owner indication on playlist page
:hammer_and_wrench: html website title
:hammer_and_wrench: nav link order in navbar
* * *
"Create a playlist" is enhenced in navbar
this is what is looks like this
this is what is looks like 
* * *
A playlist page with no track
A playlist page with at least one track
* * *

46 general visual (v1)

---

README.md

closes #71 
:exclamation: if updates during the weekend, please do update readme as well (especially the "currently available user experience" section)

#71 readme

---

src/components/Player/index.jsx
src/components/PlaylistTable/index.jsx
src/pages/Playlist/index.jsx
src/services/APIManager/index.jsx

* * *
This branch in NOT funtional. This merge is only to ensure the repo is up to date with our work in progress
* * *
related to [this](https://github.com/MixUpTeam/MixUpFront/issues/67) issue but not closed
🛠️  variable naming according to convention
➖  first row highlight coz current track is no longer in list
🛠️  current track now receives real response from back
❗ dispatch response from player

67 separate current track from track list

---

package-lock.json
package.json
src/components/Player/index.jsx
src/components/Player/styles.scss
src/components/PlaylistTable/index.jsx
src/pages/Playlist/index.jsx
src/pages/Playlist/styles.scss
src/redux/index.js
src/redux/tracklist/tracklistActions.js
src/redux/tracklist/tracklistReducer.js
src/redux/tracklist/tracklistType.js
src/services/APIManager/index.jsx

:exclamation: THIS BRANCH IS NOT FUNTIONAL. This PR is only to update the master with our latest working progress
for further details, see [this](https://github.com/MixUpTeam/MixUpFront/pull/75) PR

update master with latest status in development

---

src/components/Player/index.jsx
src/components/PlaylistTable/index.jsx
src/constants/index.js
src/pages/NewPlaylist/index.jsx
src/pages/Playlist/index.jsx
src/redux/index.js
src/redux/tracklist/tracklistActions.js
src/redux/tracklist/tracklistReducer.js
src/redux/tracklist/tracklistType.js
src/services/APIManager/index.jsx

closes #77
**Changes**
:heavy_plus_sign: [add] new condition before passing the rows in the table
:heavy_minus_sign: [delete] createTrack redux action
:heavy_minus_sign: [delete] all console.log
:hammer_and_wrench: [change] conditions into useEffect
:hammer_and_wrench: [fixup] updated_at was not sort into the back
:hammer_and_wrench: [fixup] transition action triggered by setTimeout event instead of callback
* * *

#77 render view playlist table back order
